//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svision.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Svision.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 校准单元 的本地化字符串。
        /// </summary>
        internal static string CalibrationUnit {
            get {
                return ResourceManager.GetString("CalibrationUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 背景消除 的本地化字符串。
        /// </summary>
        internal static string CalibrationUnitBackgroundRemove {
            get {
                return ResourceManager.GetString("CalibrationUnitBackgroundRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像闭运算 的本地化字符串。
        /// </summary>
        internal static string CalibrationUnitCloseOperate {
            get {
                return ResourceManager.GetString("CalibrationUnitCloseOperate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 色彩转换 的本地化字符串。
        /// </summary>
        internal static string CalibrationUnitColorConversion {
            get {
                return ResourceManager.GetString("CalibrationUnitColorConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 频域滤波 的本地化字符串。
        /// </summary>
        internal static string CalibrationUnitFreqDomainFilter {
            get {
                return ResourceManager.GetString("CalibrationUnitFreqDomainFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 直方图均衡化 的本地化字符串。
        /// </summary>
        internal static string CalibrationUnitHistogramEqualization {
            get {
                return ResourceManager.GetString("CalibrationUnitHistogramEqualization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像膨胀 的本地化字符串。
        /// </summary>
        internal static string CalibrationUnitImageDilation {
            get {
                return ResourceManager.GetString("CalibrationUnitImageDilation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中值滤波 的本地化字符串。
        /// </summary>
        internal static string CalibrationUnitMedianFilter {
            get {
                return ResourceManager.GetString("CalibrationUnitMedianFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像形态学处理 的本地化字符串。
        /// </summary>
        internal static string CalibrationUnitMorphologyProcessing {
            get {
                return ResourceManager.GetString("CalibrationUnitMorphologyProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像开运算 的本地化字符串。
        /// </summary>
        internal static string CalibrationUnitOpenOperate {
            get {
                return ResourceManager.GetString("CalibrationUnitOpenOperate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 锐化滤波 的本地化字符串。
        /// </summary>
        internal static string CalibrationUnitSharpenFilter {
            get {
                return ResourceManager.GetString("CalibrationUnitSharpenFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像平滑 的本地化字符串。
        /// </summary>
        internal static string CalibrationUnitSmooth {
            get {
                return ResourceManager.GetString("CalibrationUnitSmooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 二值化 的本地化字符串。
        /// </summary>
        internal static string CalibrationUnitThreshold {
            get {
                return ResourceManager.GetString("CalibrationUnitThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入单元 的本地化字符串。
        /// </summary>
        internal static string InputUnit {
            get {
                return ResourceManager.GetString("InputUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机输入 的本地化字符串。
        /// </summary>
        internal static string InputUnitCameraInput {
            get {
                return ResourceManager.GetString("InputUnitCameraInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件输入 的本地化字符串。
        /// </summary>
        internal static string InputUnitFileInput {
            get {
                return ResourceManager.GetString("InputUnitFileInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测量单元 的本地化字符串。
        /// </summary>
        internal static string MeasureUnit {
            get {
                return ResourceManager.GetString("MeasureUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可变尺寸形状搜索 的本地化字符串。
        /// </summary>
        internal static string MeasureUnitAnisoShapeSearch {
            get {
                return ResourceManager.GetString("MeasureUnitAnisoShapeSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BLOB分析 的本地化字符串。
        /// </summary>
        internal static string MeasureUnitBlobAnalasis {
            get {
                return ResourceManager.GetString("MeasureUnitBlobAnalasis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字符识别 的本地化字符串。
        /// </summary>
        internal static string MeasureUnitCharacter {
            get {
                return ResourceManager.GetString("MeasureUnitCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缺陷检测 的本地化字符串。
        /// </summary>
        internal static string MeasureUnitDefectDetect {
            get {
                return ResourceManager.GetString("MeasureUnitDefectDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 边缘扫描 的本地化字符串。
        /// </summary>
        internal static string MeasureUnitEdgeScan {
            get {
                return ResourceManager.GetString("MeasureUnitEdgeScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读码 的本地化字符串。
        /// </summary>
        internal static string MeasureUnitReadCode {
            get {
                return ResourceManager.GetString("MeasureUnitReadCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 形状搜索 的本地化字符串。
        /// </summary>
        internal static string MeasureUnitShapeSearch {
            get {
                return ResourceManager.GetString("MeasureUnitShapeSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空指令 的本地化字符串。
        /// </summary>
        internal static string NullFBD {
            get {
                return ResourceManager.GetString("NullFBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出单元 的本地化字符串。
        /// </summary>
        internal static string OutputUnit {
            get {
                return ResourceManager.GetString("OutputUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 串行输出 的本地化字符串。
        /// </summary>
        internal static string OutputUnitSerialOutput {
            get {
                return ResourceManager.GetString("OutputUnitSerialOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 圆 {
            get {
                object obj = ResourceManager.GetObject("圆", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 多边形 {
            get {
                object obj = ResourceManager.GetObject("多边形", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 方形 {
            get {
                object obj = ResourceManager.GetObject("方形", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 椭圆 {
            get {
                object obj = ResourceManager.GetObject("椭圆", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
